### ISSUE TITLE
Popover component renders out of the top of the screen when content is too long

### ISSUE THREAD

**Issue by ijasm** [LifeSG/react-design-system#247]
**Component**
Popover

**Describe the bug**
The popover element renders out of the top of the screen when the content is too long. The z-index needs to be increased as well as it is rendering under the LifeSG navigation bar.

**To Reproduce**
Render the popover component with a long chunk of text in the content body

**Expected behavior**
It should render out of the top of the screen

**Screenshots**
![Screenshot 2023-07-18 at 10 13 47 AM](https://github.com/LifeSG/react-design-system/assets/6988326/49e9d1d5-d5ab-4d0c-b24b-4a4f63ef663e)

**Comment by qroll** [comment]
Closed by #253
