### ISSUE TITLE
Popover component's modal (in mobile view) does not scroll when content is too long

### ISSUE THREAD

**Issue by ijasm** [LifeSG/react-design-system#264]
**Component**
Popover

**Describe the bug**
Popover modal's (mobile view) content is hidden when it overflows, instead of being scrollable

**To Reproduce**
Set popover component to have long content.

**Expected behavior**
Popover modal should scroll when content is too long.

**Screenshots**
![Screenshot 2023-07-31 at 2 37 08 PM](https://github.com/LifeSG/react-design-system/assets/6988326/b4517765-7c14-4b99-a718-26fa61ecc882)

**Comment by qroll** [comment]
Closed by #266
