### ISSUE TITLE
Lagginess on components with dropdown on SOE devices using Edge Browser

### ISSUE THREAD

**Issue by nobeltws** [LifeSG/react-design-system#394]
**Component**
Form.Select
Form.DateInput
Form.DateRangeInput
Form.MultiSelect
Form.NestedMultiSelect
Form.NestedSelect
Form.PhoneNumberInput
Form.PredictiveTextInput
Form.RangeSelect
Form.TimeRangePicker
Form.Timepicker
Accordion

**Describe the bug**
When using Edge browser on SOE device, we experience that these components have very slow animation. The CPU and memory usage is observed to be healthy. As SOE device only allows Edge browser, there was no way to test out if the behaviour is happening on other browsers.

**To Reproduce**

1. Go to 'https://designsystem.life.gov.sg/react/index.html?path=/docs/form-dateinput--docs'
2. Click on the sample component to trigger the dropdown animation
3. Observe that the animation is very slow and takes longer than expected to fully complete

**Expected behavior**
The animation should be smooth and should complete within 1 second.

**Screenshots**
(Refer to video recording posted in github-lifesg-react-design-system channel)

**Additional context**
This issue was raised by users of BookingSG that utilises Design System components.

**Comment by keithtxw** [comment]
Found out that issue was due to a problem in `react-spring@v9.6.0`. As such, we have bumped it to the latest version (`v9.7.3`) and confirmed that issue was resolved.

For more details, refer to this [PR](https://github.com/LifeSG/react-design-system/pull/397)
